# Binary predictors- same as dummies, but for logical regression

## Import relevant libaries 

In [2]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

## Load data

In [3]:
raw_data = pd.read_csv("Binary Predictors.csv")
raw_data

SAT Admitted  Gender
0    1363       No    Male
1    1792      Yes  Female
2    1954      Yes  Female
3    1653       No    Male
4    1593       No    Male
..    ...      ...     ...
163  1722      Yes  Female
164  1750      Yes    Male
165  1555       No    Male
166  1524       No    Male
167  1461       No    Male

[168 rows x 3 columns]

In [4]:
data = raw_data.copy()
data["Admitted"]= data["Admitted"].map({"Yes":1,"No":0})
data["Gender"] = data["Gender"].map({"Female":1,"Male":0})
data
## Male is the baceline in the reference group- in statistical lingo 

SAT  Admitted  Gender
0    1363         0       0
1    1792         1       1
2    1954         1       1
3    1653         0       0
4    1593         0       0
..    ...       ...     ...
163  1722         1       1
164  1750         1       0
165  1555         0       0
166  1524         0       0
167  1461         0       0

[168 rows x 3 columns]

## Declare dependant and independant variables 

In [5]:
y = data["Admitted"]
x1 = data["Gender"]

## Regression

In [6]:
x = sm.add_constant(x1)
reg_log = sm.Logit(y,x)
results_log = reg_log.fit()
results_log.summary()

Optimization terminated successfully.
         Current function value: 0.572260
         Iterations 5


C:\Users\jackm\Anaconda3\lib\site-packages\statsmodels\tsa\tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:               Admitted   No. Observations:                  168
Model:                          Logit   Df Residuals:                      166
Method:                           MLE   Df Model:                            1
Date:                Thu, 07 Apr 2022   Pseudo R-squ.:                  0.1659
Time:                        12:27:26   Log-Likelihood:                -96.140
converged:                       True   LL-Null:                       -115.26
Covariance Type:            nonrobust   LLR p-value:                 6.283e-10
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.6436      0.222     -2.901      0.004      -1.078      -0.209
Gender         2.0786      0.363      5.727      0.000       1.367       2.790
==============================================================================
"""

In [7]:
## p value and gender variable are significant 

In [8]:
## log (odds)= -0.64 + 2.08 * Gender 
## log(odds2) = -0.64 + 2.08 * Gender 2
## log(odds1) = -0.64 + 2.08 * Gender 1
## log odds2/log odds 1 = 2.08 * (Gender 2- Gender 1) = 2.08 * (1-0)
## Gender 2 or 1 can only equal 1 or 0, so Gender 2 = 1, Gender 1 = 0 
## log odds 2/1 = 2.08

In [9]:
np.exp(2.0786)

7.993270498536442

In [10]:
## odds of female being admitted are 7.99 times odds of male

In [11]:
y = data["Admitted"]
x2 = data[["SAT","Gender"]]

In [12]:
x = sm.add_constant(x2)
reg_log = sm.Logit(y,x)
results_log = reg_log.fit()
results_log.summary()

C:\Users\jackm\Anaconda3\lib\site-packages\statsmodels\tsa\tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


Optimization terminated successfully.
         Current function value: 0.120117
         Iterations 10


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:               Admitted   No. Observations:                  168
Model:                          Logit   Df Residuals:                      165
Method:                           MLE   Df Model:                            2
Date:                Thu, 07 Apr 2022   Pseudo R-squ.:                  0.8249
Time:                        12:27:27   Log-Likelihood:                -20.180
converged:                       True   LL-Null:                       -115.26
Covariance Type:            nonrobust   LLR p-value:                 5.118e-42
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const        -68.3489     16.454     -4.154      0.000    -100.598     -36.100
SAT            0.0406      0.010      4.129      0.000       0.021       0.060
Gender         1.9449      0.846      2.299      0.022       0.287       3.603
==============================================================================

Possibly complete quasi-separation: A fraction 0.27 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.
"""

In [13]:
## higher log likehood means it is a better model 
## gender is significant but no longer three zero's, plus new coefficent 
## given same SAT score, female is 7 times higher odds to get admitted 
## in this particular university, it is much easier for females to enter 
## always interpret results based on context 

In [14]:
np.exp(1.9449)

6.992932526814459

In [16]:
np.set_printoptions(formatter={"float": lambda x: '{0:0.2f}'.format(x)})
results_log.predict()

array([0.00, 1.00, 1.00, 0.23, 0.02, 0.99, 1.00, 1.00, 1.00, 0.01, 1.00,
       1.00, 0.76, 0.00, 0.60, 1.00, 0.11, 0.12, 0.51, 1.00, 1.00, 1.00,
       0.00, 0.01, 0.97, 1.00, 0.48, 0.99, 1.00, 0.99, 0.00, 0.83, 0.25,
       1.00, 1.00, 1.00, 0.31, 1.00, 0.23, 0.00, 0.02, 0.45, 1.00, 0.00,
       0.99, 0.00, 0.99, 0.00, 0.00, 0.01, 0.00, 1.00, 0.92, 0.02, 1.00,
       0.00, 0.37, 0.98, 0.12, 1.00, 0.00, 0.78, 1.00, 1.00, 0.98, 0.00,
       0.00, 0.00, 1.00, 0.00, 0.78, 0.12, 0.00, 0.99, 1.00, 1.00, 0.00,
       0.30, 1.00, 1.00, 0.00, 1.00, 1.00, 0.85, 1.00, 1.00, 0.00, 1.00,
       1.00, 0.89, 0.83, 0.00, 0.98, 0.97, 0.00, 1.00, 1.00, 0.03, 0.99,
       0.96, 1.00, 0.00, 1.00, 0.01, 0.01, 1.00, 1.00, 1.00, 0.00, 0.00,
       0.02, 0.33, 0.00, 1.00, 0.09, 0.00, 0.97, 0.00, 0.75, 1.00, 1.00,
       0.01, 0.01, 0.00, 1.00, 0.00, 0.99, 0.57, 0.54, 0.87, 0.83, 0.00,
       1.00, 0.00, 0.00, 0.00, 1.00, 0.04, 0.00, 0.01, 1.00, 0.99, 0.52,
       1.00, 1.00, 0.05, 0.00, 0.00, 0.00, 0.68, 1.

In [17]:
## values above are part of the pi side of odds formula
## probabilities
## values below 0.5 can be rounded down, values above can be rounded up

In [18]:
np.array(data["Admitted"])
## if 80% of below values (actual values) match above (actual values), we can say model has 80% accuracy

array([0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0], dtype=int64)

In [19]:
results_log.pred_table()
## compares actual to predicted values

array([[69.00, 5.00],
       [4.00, 90.00]])

In [22]:
cm_df = pd.DataFrame(results_log.pred_table())
cm_df.columns = ["Predicted 0","Predicted 1"]
cm_df = cm_df.rename(index={0:"Actual 0",1: "Actual 1"})
cm_df
## creates confusion matrix- shows how confused our model was, but gave us a 94.6% accuracy- 90 + 69 + 9, then accurate /total

Predicted 0  Predicted 1
Actual 0         69.0          5.0
Actual 1          4.0         90.0

In [23]:
## for 69 observations model predicted 0 when was 0, 90 observations it predicted 1 when was 1

In [27]:
cm = np.array(cm_df)
accuracy_train = (cm[0,0] + cm[1,1])/cm.sum()
accuracy_train

0.9464285714285714

## Testing the model and assessing its accuracy 

In [30]:
test = pd.read_csv("Test data.csv")
test
## this is part of original data, 90/10 split. 19 observations for test data

SAT Admitted  Gender
0   1323       No    Male
1   1725      Yes  Female
2   1762      Yes  Female
3   1777      Yes    Male
4   1665       No    Male
5   1556      Yes  Female
6   1731      Yes  Female
7   1809      Yes  Female
8   1930      Yes  Female
9   1708      Yes    Male
10  1970      Yes  Female
11  2039      Yes  Female
12  1681      Yes  Female
13  1444       No    Male
14  1726       No    Male
15  1876      Yes  Female
16  1485       No    Male
17  1500       No  Female
18  1900      Yes    Male

In [32]:
test["Admitted"] = test["Admitted"].map({"Yes":1,"No":0})
test["Gender"]= test["Gender"].map({"Female":1,"Male":0})
test

SAT  Admitted  Gender
0   1323         0       0
1   1725         1       1
2   1762         1       1
3   1777         1       0
4   1665         0       0
5   1556         1       1
6   1731         1       1
7   1809         1       1
8   1930         1       1
9   1708         1       0
10  1970         1       1
11  2039         1       1
12  1681         1       1
13  1444         0       0
14  1726         0       0
15  1876         1       1
16  1485         0       0
17  1500         0       1
18  1900         1       0

In [33]:
x
## order of variables is fundamental, if order is wrong, so will be the prediction

const   SAT  Gender
0      1.0  1363       0
1      1.0  1792       1
2      1.0  1954       1
3      1.0  1653       0
4      1.0  1593       0
..     ...   ...     ...
163    1.0  1722       1
164    1.0  1750       0
165    1.0  1555       0
166    1.0  1524       0
167    1.0  1461       0

[168 rows x 3 columns]

In [36]:
test_actual = test["Admitted"]
test_data = test.drop(["Admitted"],axis=1)
test_data = sm.add_constant(test_data)
# test data = test_data[x.columns.values]- if needed to reorganise columns on my own
test_data

C:\Users\jackm\Anaconda3\lib\site-packages\statsmodels\tsa\tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


const   SAT  Gender
0     1.0  1323       0
1     1.0  1725       1
2     1.0  1762       1
3     1.0  1777       0
4     1.0  1665       0
5     1.0  1556       1
6     1.0  1731       1
7     1.0  1809       1
8     1.0  1930       1
9     1.0  1708       0
10    1.0  1970       1
11    1.0  2039       1
12    1.0  1681       1
13    1.0  1444       0
14    1.0  1726       0
15    1.0  1876       1
16    1.0  1485       0
17    1.0  1500       1
18    1.0  1900       0

In [50]:
def confusion_matrix(data,actual_values,model):
    pred_values = model.predict(data)
    bins = np.array([0,0.5,1])
    cm = np.histogram2d(actual_values,pred_values,bins=bins)[0]
    accuracy = (cm[0,0]+cm[1,1])/cm.sum()
    return cm, accuracy

In [51]:
cm = confusion_matrix(test_data,test_actual,results_log)
cm
## left part is confusion matrix, right part is accuracy 
## accuracy with training data is always higher than test, as model tries to fit data as best as possible
# but test data the model has not seen prevents overfitting, and make conclusions based on that  

(array([[5.00, 1.00],
        [1.00, 12.00]]),
 0.8947368421052632)

In [60]:
cm_df = pd.DataFrame(cm[0])
cm_df.columns = ["Predicted 0","Predicted 1"]
cm_df = cm_df.rename(index={0: "Actual 0", 1: "Actual 1"})
cm_df

Predicted 0  Predicted 1
Actual 0          5.0          1.0
Actual 1          1.0         12.0

In [65]:
# mislclassification rate is opposite of accuracy rate 
## misclassification rate = missclassified elements/total elements 
print("Missclassification rate:  " +str((1+1)/19))

Missclassification rate:  0.10526315789473684


In [67]:
print(0.10526315789473684 * 100)

10.526315789473683
