# Scalers, Vectors and Matrices 

## Import the relevant libraries 

In [28]:
import numpy as np

## Declaring Scalers, vectors and matrices

### Scalers

In [29]:
s = 5

In [30]:
s

5

### Vectors 

In [31]:
v = np.array([5,-2,4])

In [32]:
v 
## by default, v is a row vector 

array([ 5, -2,  4])

### Matrices 

In [33]:
m = np.array([[5,12,6],[-3,0,14]])
m
## matrix is two vectors combined, remember to double bracket them 

array([[ 5, 12,  6],
       [-3,  0, 14]])

### Data types

In [34]:
type(s)

int

In [35]:
type(v) 
## nd array = n-dimension array

numpy.ndarray

In [36]:
type(m)

numpy.ndarray

In [37]:
s_array = np.array(5)

In [38]:
type(s_array)

numpy.ndarray

### Data shapes

In [39]:
m.shape

(2, 3)

In [40]:
v.shape
## indicates this object with 3 ordered elements 

(3,)

In [41]:
s.shape

AttributeError: 'int' object has no attribute 'shape'

In [ ]:
s_array.shape
# scaler has 0 dimensional object, so has no shape 

### Creating column vector 

In [ ]:
v.reshape(1,3)
## row vector

In [ ]:
v.reshape(3,1)
# column vector

In [ ]:
## scaler is matrix of length 1, or 1x1 matrix, vector is collection of scalers, matrix is collection of scalers and vectors 
## vector is length m x 1, matrix is length m x n 
# scalers, matrices and vectors are all tensors of rank 0, 1 and 2 
## tensors are generalisations of concepts seen so far 
## tensor of rank 3 has dimensions k by m by n, thought of as collection of matrices 

In [ ]:
## can add matrices if they have the same dimensions, same rules for subtraction

### Adding matrices 

In [43]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [44]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [45]:
m3 = m1+ m2
m3

array([[14, 20, 13],
       [-2,  3,  9]])

In [57]:
m4 = np.array([[5,3],[-2,4]])
m4

array([[ 5,  3],
       [-2,  4]])

In [58]:
m5 = np.array([[7,-5],[3,8]])
m5

array([[ 7, -5],
       [ 3,  8]])

In [60]:
m6 = m4- m5
m6


array([[-2,  8],
       [-5, -4]])

In [61]:
## vectors have same rules, but we only care about length

## Errors when adding scalers, vectors, and matrices in Python

### Addition

### Addition of scalers 

In [62]:
5 +5 

10

In [63]:
10 - 4

6

In [ ]:
## to add scalers or vectors, their forms must match 

### Addition of matrices 

In [64]:
m1 - m5

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [ ]:
## value error because forms are different 

### Addition of vectors 

### Exceptions(additon with scalers)

In [65]:
m1 + 1
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [ ]:
## mathmatically not allowed, but in python it works 

### Transpose a vector

In [ ]:
## transposing means changing column vector to row. Contents don't change only position 
## if transpose a vector twice, you get x, or same object before you transposed it
## m by n matrix becomes n by m matrix when transposed 

In [66]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [68]:
A.T
## transposing 

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

### Transposing Scalers 

In [69]:
s = np.array([5])
s

array([5])

In [70]:
s.T

array([5])

### Transposing vectors 

In [71]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [72]:
x.T

array([1, 2, 3])

In [73]:
x.shape

(3,)

In [74]:
## 1d array doesn't get transposed

In [75]:
x_reshaped = x.reshape(1,3)
x_reshaped

array([[1, 2, 3]])

In [76]:
x_reshaped.T

array([[1],
       [2],
       [3]])

### Multiplying scaler by scaler

In [78]:
a = 5 * 3
a

15

### Multiplying vectors

In [79]:
## can either get dot product or tensor product 

In [80]:
## dot product creates a scaler product from vectors, since adding vectors creates scalers 

In [84]:
y = np.array([2,8,-4])

In [90]:
z = np.array([1,-7,3])

In [91]:
np.dot(y,z)


-66

### Multiplying scaler by vector 

In [92]:
product1 = 5 *z

In [93]:
product1

array([  5, -35,  15])

### Multiplying scaler by matrix

In [96]:
A = np.array([[5,12,6],[-3,0,14]]) 
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [97]:
A * 3

array([[15, 36, 18],
       [-9,  0, 42]])

In [100]:
B = np.array([[2,-1],[8,0],[3,0]])
B

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

### Multipling matrix by matrix 

In [98]:
# matrix can only be mulplied if it is an m by n with an n by k matrix
## second dimension of first matrix must match first dimension of second matrix
## e.g 2 by 3 by a 3 by 1
## product of m by n with n by k is m by k matrix 
## called compatability measure 
## dot product is row x column vectors

In [101]:
np.dot(A,B)


array([[124,  -5],
       [ 36,   3]])