# Scalers, Vectors and Matrices 

## Import the relevant libraries 

In [3]:
import numpy as np

## Declaring Scalers, vectors and matrices

### Scalers

In [4]:
s = 5

In [5]:
s

5

### Vectors 

In [7]:
v = np.array([5,-2,4])

In [8]:
v 
## by default, v is a row vector 

array([ 5, -2,  4])

### Matrices 

In [11]:
m = np.array([[5,12,6],[-3,0,14]])
m
## matrix is two vectors combined, remember to double bracket them 

array([[ 5, 12,  6],
       [-3,  0, 14]])

### Data types

In [12]:
type(s)

int

In [13]:
type(v) 
## nd array = n-dimension array

numpy.ndarray

In [14]:
type(m)

numpy.ndarray

In [16]:
s_array = np.array(5)

In [18]:
type(s_array)

numpy.ndarray

### Data shapes

In [20]:
m.shape

(2, 3)

In [21]:
v.shape
## indicates this object with 3 ordered elements 

(3,)

In [25]:
s.shape

AttributeError: 'int' object has no attribute 'shape'

In [26]:
s_array.shape
# scaler has 0 dimensional object, so has no shape 

()

### Creating column vector 

In [23]:
v.reshape(1,3)
## row vector

array([[ 5, -2,  4]])

In [24]:
v.reshape(3,1)
# column vector

array([[ 5],
       [-2],
       [ 4]])

In [ ]:
## scaler is matrix of length 1, or 1x1 matrix, vector is collection of scalers, matrix is collection of scalers and vectors 
## vector is length m x 1, matrix is length m x n 
# scalers, matrices and vectors are all tensors of rank 0, 1 and 2 
## tensors are generalisations of concepts seen so far 
## tensor of rank 3 has dimensions k by m by n, thought of as collection of matrices 